version: 2
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/my-utils
    branches:
      only:
        - master
    steps:
        - checkout
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
        - run: npm install
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
        - run: npm install
        - run: npm test
        - run: npm i -g codecov
        - run: codecov